In [ ]:
# %pip install numpy
# %pip install pandas

Collecting numpy
  Downloading numpy-2.3.4-cp313-cp313-win_amd64.whl.metadata (60 kB)
Downloading numpy-2.3.4-cp313-cp313-win_amd64.whl (12.8 MB)
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.8 MB 2.2 MB/s eta 0:00:06
   --- ------------------------------------ 1.0/12.8 MB 1.9 MB/s eta 0:00:07
   ---- ----------------------------------- 1.3/12.8 MB 1.9 MB/s eta 0:00:06
   ----- ---------------------------------- 1.8/12.8 MB 1.9 MB/s eta 0:00:06
   ------- -------------------------------- 2.4/12.8 MB 2.0 MB/s eta 0:00:06
   --------- ------------------------------ 2.9/12.8 MB 2.0 MB/s eta 0:00:05
   ---------- ----------------------------- 3.4/12.8 MB 2.1 MB/s eta 0:00:05
   ------------- -------------------------- 4.2/12.8 MB 2.3 MB/s eta 0:00:04
   --------------- ------------------------ 5.0/12.8 MB 2.5 MB/s eta 0:00:04
   ------------------ --------------------- 5.8/12.8 MB 2.6 MB/s eta 0:00:03
   --------------------- ------------------ 6.8/12.8 MB 2.8 MB/s eta 0:00:03
   ----------------------- ---------------- 7.6/12.8 MB 3.0 MB/s eta 0:00:02
   ------------------------ --------------- 7.9/12.8 MB 2.8 MB/s eta 0:00:02
   ------------------------- -------------- 8.1/12.8 MB 2.8 MB/s eta 0:00:02
   ------------------------- -------------- 8.1/12.8 MB 2.8 MB/s eta 0:00:02
   -------------------------- ------------- 8.4/12.8 MB 2.4 MB/s eta 0:00:02
   --------------------------- ------------ 8.9/12.8 MB 2.4 MB/s eta 0:00:02
   ---------------------------- ----------- 9.2/12.8 MB 2.3 MB/s eta 0:00:02
   ----------------------------- ---------- 9.4/12.8 MB 2.4 MB/s eta 0:00:02
   ------------------------------- -------- 10.2/12.8 MB 2.3 MB/s eta 0:00:02
   --------------------------------- ------ 10.7/12.8 MB 2.4 MB/s eta 0:00:01
   ----------------------------------- ---- 11.3/12.8 MB 2.4 MB/s eta 0:00:01
   ------------------------------------ --- 11.5/12.8 MB 2.4 MB/s eta 0:00:01
   ------------------------------------ --- 11.5/12.8 MB 2.4 MB/s eta 0:00:01
   ------------------------------------- -- 12.1/12.8 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.8 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------- 12.8/12.8 MB 2.2 MB/s eta 0:00:00
Installing collected packages: numpy
Successfully installed numpy-2.3.4
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting pandas
  Downloading pandas-2.3.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in e:\projects\laptop\model\venv\lib\site-packages (from pandas) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\projects\laptop\model\venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: tzdata>=2022.7 in e:\projects\laptop\model\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in e:\projects\laptop\model\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.3-cp313-cp313-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.0 MB 1.1 MB/s eta 0:00:10
   - -------------------------------------- 0.5/11.0 MB 1.1 MB/s eta 0:00:10
   -- ------------------------------------- 0.8/11.0 MB 1.1 MB/s eta 0:00:10
   --- ------------------------------------ 1.0/11.0 MB 1.0 MB/s eta 0:00:10
   ---- ----------------------------------- 1.3/11.0 MB 1.1 MB/s eta 0:00:09
   ------ --------------------------------- 1.8/11.0 MB 1.2 MB/s eta 0:00:08
   ------- -------------------------------- 2.1/11.0 MB 1.3 MB/s eta 0:00:07
   -------- ------------------------------- 2.4/11.0 MB 1.3 MB/s eta 0:00:07
   ---------- ----------------------------- 2.9/11.0 MB 1.4 MB/s eta 0:00:06
   ------------ --------------------------- 3.4/11.0 MB 1.5 MB/s eta 0:00:06
   -------------- ------------------------- 3.9/11.0 MB 1.5 MB/s eta 0:00:05
   ---------------- ----------------------- 4.5/11.0 MB 1.6 MB/s eta 0:00:05
   ------------------ --------------------- 5.0/11.0 MB 1.7 MB/s eta 0:00:04
   -------------------- ------------------- 5.8/11.0 MB 1.8 MB/s eta 0:00:03
   ----------------------- ---------------- 6.6/11.0 MB 2.0 MB/s eta 0:00:03
   --------------------------- ------------ 7.6/11.0 MB 2.1 MB/s eta 0:00:02
   ----------------------------- ---------- 8.1/11.0 MB 2.2 MB/s eta 0:00:02
   ------------------------------- -------- 8.7/11.0 MB 2.2 MB/s eta 0:00:02
   ----------------------------------- ---- 9.7/11.0 MB 2.3 MB/s eta 0:00:01
   ----------------------------------- ---- 9.7/11.0 MB 2.3 MB/s eta 0:00:01
   ----------------------------------- ---- 9.7/11.0 MB 2.3 MB/s eta 0:00:01
   ------------------------------------ --- 10.0/11.0 MB 2.1 MB/s eta 0:00:01
   ------------------------------------- -- 10.2/11.0 MB 2.0 MB/s eta 0:00:01
   -------------------------------------- - 10.5/11.0 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------  10.7/11.0 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 2.0 MB/s eta 0:00:00
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Installing collected packages: pytz, pandas
Successfully installed pandas-2.3.3 pytz-2025.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import numpy as np
import pandas as pd

In [8]:
data=pd.read_csv("laptop_price.csv", encoding='latin-1')

In [9]:
data.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         1303 non-null   int64
 1   Company           1303 non-null   object
 2   Product           1303 non-null   object
 3   TypeName          1303 non-null   object
 4   Inches            1303 non-null   float64
 5   ScreenResolution  1303 non-null   object
 6   Cpu               1303 non-null   object
 7   Ram               1303 non-null   object
 8   Gpu               1303 non-null   object
 9   OpSys             1303 non-null   object
 10  Weight            1303 non-null   object
 11  Price_euros       1303 non-null   float64
dtypes: float64(2), int64(1), object(9)
memory usage: 122.3+ KB

In [11]:
data.tail(10)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros
1293,1311,Lenovo,IdeaPad Y700-15ISK,Notebook,15.6,IPS Panel Full HD 1920x1080,Intel Core i7 6700HQ 2.6GHz,8GB,Nvidia GeForce GTX 960M,Windows 10,2.6kg,899.00
1294,1312,HP,Pavilion 15-AW003nv,Notebook,15.6,Full HD 1920x1080,AMD A9-Series 9410 2.9GHz,6GB,AMD Radeon R7 M440,Windows 10,2.04kg,549.99
1295,1313,Dell,Inspiron 3567,Notebook,15.6,1366x768,Intel Core i7 7500U 2.7GHz,8GB,AMD Radeon R5 M430,Linux,2.3kg,805.99
1296,1314,HP,Stream 11-Y000na,Netbook,11.6,1366x768,Intel Celeron Dual Core N3060 1.6GHz,2GB,Intel HD Graphics 400,Windows 10,1.17kg,209.00
1297,1315,Asus,X556UJ-XO044T (i7-6500U/4GB/500GB/GeForce,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,4GB,Nvidia GeForce 920M,Windows 10,2.2kg,720.32
1298,1316,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,Intel HD Graphics 520,Windows 10,1.8kg,638.00
1299,1317,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,Intel HD Graphics 520,Windows 10,1.3kg,1499.00
1300,1318,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,Intel HD Graphics,Windows 10,1.5kg,229.00
1301,1319,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,AMD Radeon R5 M330,Windows 10,2.19kg,764.00
1302,1320,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,Intel HD Graphics,Windows 10,2.2kg,369.00

In [12]:
data.shape

(1303, 12)

In [15]:
data.isnull().sum()

laptop_ID           0
Company             0
Product             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Gpu                 0
OpSys               0
Weight              0
Price_euros         0
dtype: int64

In [16]:
data.head(2)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94

In [17]:
data['Ram']=data['Ram'].str.replace('GB','').astype('int32')
data['Weight']=data['Weight'].str.replace('kg','').astype('float32')

In [18]:
data.head(2)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,macOS,1.37,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,macOS,1.34,898.94

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         1303 non-null   int64
 1   Company           1303 non-null   object
 2   Product           1303 non-null   object
 3   TypeName          1303 non-null   object
 4   Inches            1303 non-null   float64
 5   ScreenResolution  1303 non-null   object
 6   Cpu               1303 non-null   object
 7   Ram               1303 non-null   int32
 8   Gpu               1303 non-null   object
 9   OpSys             1303 non-null   object
 10  Weight            1303 non-null   float32
 11  Price_euros       1303 non-null   float64
dtypes: float32(1), float64(2), int32(1), int64(1), object(7)
memory usage: 112.1+ KB

In [22]:
data.corr(numeric_only=True)['Price_euros']

laptop_ID      0.067830
Inches         0.068197
Ram            0.743007
Weight         0.210370
Price_euros    1.000000
Name: Price_euros, dtype: float64

In [25]:
data['Company'].value_counts()

Company
Dell         297
Lenovo       297
HP           274
Asus         158
Acer         103
MSI           54
Toshiba       48
Apple         21
Samsung        9
Mediacom       7
Razer          7
Microsoft      6
Vero           4
Xiaomi         4
Chuwi          3
Fujitsu        3
Google         3
LG             3
Huawei         2
Name: count, dtype: int64

In [28]:
def add_company(input):
    if input=='Samsung' or input=='Razer' or input=='Mediacom' or input=='Microsoft' or input=='Vero' or input=='Xiaomi' or input=='Chuwi' or input=='Fujitsu' or input=='Google' or input=='LG' or input=='Huawei':
        return 'Other'
    else:
        return input
data['Company']=data['Company'].apply(add_company)

In [29]:
data['Company'].value_counts()

Company
Dell       297
Lenovo     297
HP         274
Asus       158
Acer       103
MSI         54
Other       51
Toshiba     48
Apple       21
Name: count, dtype: int64

In [31]:
len(data['Product'].value_counts())

618

In [32]:
data['TypeName'].value_counts()

TypeName
Notebook              727
Gaming                205
Ultrabook             196
2 in 1 Convertible    121
Workstation            29
Netbook                25
Name: count, dtype: int64

In [34]:
len(data['ScreenResolution'].value_counts())

40

In [35]:
data['Touchscreen']=data['ScreenResolution'].apply(lambda x:1 if 'Touchscreen' in x else 0)
data['Ips']=data['ScreenResolution'].apply(lambda x:1 if 'Ips' in x else 0)

In [36]:
data.head(2)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Touchscreen,Ips
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,0,0
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,macOS,1.34,898.94,0,0

In [39]:
len(data['Cpu'].value_counts())

118

In [40]:
data['cpu_name']=data['Cpu'].apply(lambda x:" ".join(x.split()[0:3]))

In [41]:
data['cpu_name'].value_counts()

cpu_name
Intel Core i7               527
Intel Core i5               423
Intel Core i3               136
Intel Celeron Dual           80
Intel Pentium Quad           27
Intel Core M                 19
AMD A9-Series 9420           12
AMD A6-Series 9220            8
Intel Celeron Quad            8
AMD A12-Series 9720P          7
Intel Atom x5-Z8350           5
AMD A8-Series 7410            4
Intel Atom x5-Z8550           4
AMD A9-Series 9410            3
Intel Pentium Dual            3
AMD Ryzen 1700                3
AMD A9-Series A9-9420         2
AMD E-Series E2-9000e         2
AMD A10-Series A10-9620P      2
AMD A6-Series A6-9220         2
AMD E-Series 7110             2
AMD A10-Series 9620P          2
AMD A10-Series 9600P          2
Intel Xeon E3-1505M           2
Intel Xeon E3-1535M           2
Intel Atom X5-Z8350           2
Intel Atom x5-Z8300           1
AMD E-Series 6110             1
AMD E-Series 9000e            1
AMD E-Series E2-6110          1
AMD FX 9830P                  1
AMD Ryzen 1600                1
Intel Atom Z8350              1
AMD A6-Series 7310            1
AMD E-Series E2-9000          1
AMD A12-Series 9700P          1
AMD FX 8800P                  1
AMD A4-Series 7210            1
Samsung Cortex A72&A53        1
AMD E-Series 9000             1
Name: count, dtype: int64

In [43]:
def set_processor(name):
    if name=='Intel Core i7' or name=="Intel Core i5" or name== 'Intel Core i3':
        return name
    else:
        if name.split()[0]=='AMD':
            return 'AMD'
        else:
            return'Other'
        
data['cpu_name']=data['cpu_name'].apply(set_processor)

In [44]:
data['cpu_name'].value_counts()

cpu_name
Intel Core i7    527
Intel Core i5    423
Other            155
Intel Core i3    136
AMD               62
Name: count, dtype: int64

In [45]:
data['Gpu'].value_counts()

Gpu
Intel HD Graphics 620      281
Intel HD Graphics 520      185
Intel UHD Graphics 620      68
Nvidia GeForce GTX 1050     66
Nvidia GeForce GTX 1060     48
                          ...
Nvidia Quadro M500M          1
AMD Radeon R7 M360           1
Nvidia Quadro M3000M         1
Nvidia GeForce 960M          1
ARM Mali T860 MP4            1
Name: count, Length: 110, dtype: int64

In [46]:
data['gpu_name']=data['Gpu'].apply(lambda x:" ".join(x.split()[0:1]))

In [47]:
data['gpu_name'].value_counts()

gpu_name
Intel     722
Nvidia    400
AMD       180
ARM         1
Name: count, dtype: int64

In [48]:
data.shape

(1303, 16)

In [49]:
data=data[data['gpu_name'] != 'ARM']

In [50]:
data.shape

(1302, 16)

In [51]:
data.head(2)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Touchscreen,Ips,cpu_name,gpu_name
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,0,0,Intel Core i5,Intel
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,macOS,1.34,898.94,0,0,Intel Core i5,Intel

In [52]:
data['OpSys'].value_counts()

OpSys
Windows 10      1072
No OS             66
Linux             62
Windows 7         45
Chrome OS         26
macOS             13
Mac OS X           8
Windows 10 S       8
Android            2
Name: count, dtype: int64

In [53]:
def set_os(inpt):
    if inpt =='Windows 10' or inpt =='Windows 7' or inpt =='Windows 10 S' :
        return 'Windows'
    elif inpt =='macOS' or inpt =='Mac OS X' :
        return 'Mac'
    elif inpt =='Linux' :
        return inpt
    else :
        return 'Other'
    
data['OpSys']=data['OpSys'].apply(set_os)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_56308\2587455217.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['OpSys']=data['OpSys'].apply(set_os)

In [54]:
data['OpSys'].value_counts()

OpSys
Windows    1125
Other        94
Linux        62
Mac          21
Name: count, dtype: int64

In [55]:
data.head(2)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Touchscreen,Ips,cpu_name,gpu_name
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,Mac,1.37,1339.69,0,0,Intel Core i5,Intel
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,Mac,1.34,898.94,0,0,Intel Core i5,Intel

In [58]:
data=data.drop(columns=['laptop_ID','Inches','Product','ScreenResolution','Cpu','Gpu'])

In [59]:
data.head()

,Company,TypeName,Ram,OpSys,Weight,Price_euros,Touchscreen,Ips,cpu_name,gpu_name
0,Apple,Ultrabook,8,Mac,1.37,1339.69,0,0,Intel Core i5,Intel
1,Apple,Ultrabook,8,Mac,1.34,898.94,0,0,Intel Core i5,Intel
2,HP,Notebook,8,Other,1.86,575.00,0,0,Intel Core i5,Intel
3,Apple,Ultrabook,16,Mac,1.83,2537.45,0,0,Intel Core i7,AMD
4,Apple,Ultrabook,8,Mac,1.37,1803.60,0,0,Intel Core i5,Intel

In [60]:
data=pd.get_dummies(data)

In [61]:
data.head(2)

,Ram,Weight,Price_euros,Touchscreen,Ips,Company_Acer,Company_Apple,Company_Asus,Company_Dell,Company_HP,...,OpSys_Other,OpSys_Windows,cpu_name_AMD,cpu_name_Intel Core i3,cpu_name_Intel Core i5,cpu_name_Intel Core i7,cpu_name_Other,gpu_name_AMD,gpu_name_Intel,gpu_name_Nvidia
0,8,1.37,1339.69,0,0,False,True,False,False,False,...,False,False,False,False,True,False,False,False,True,False
1,8,1.34,898.94,0,0,False,True,False,False,False,...,False,False,False,False,True,False,False,False,True,False

In [62]:
data.shape

(1302, 32)